model_opts:
  model: PCPA_TR_VISUAL
  obs_input_type: [local_context_cnn, mask_cnn]
  apply_class_weights: True
  normalize_boxes: True
  generator: True
  t_time2vec_dim: 1
  t_num_heads: 4
  t_head_size: 128
  t_num_layers: 4 # 2
  t_dropout: 0.2
net_opts:
  num_hidden_units: 256
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: gru
  backbone: vgg19
exp_opts:
  datasets: [jaad_all, jaad_beh, pie]
  batch_size: [2, 2, 2]
  epochs: [80, 80, 80]
  lr: [5.0e-07, 5.0e-07, 5.0e-07]
