model_opts:
  model: MASK_PCPA_4_2D
  obs_input_type: [local_context_cnn, mask_cnn, pose, box, speed]
  apply_class_weights: True
  normalize_boxes: True
  generator: True
net_opts:
  num_hidden_units: 256
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: gru
  backbone: mobilenet_v2
exp_opts:
  datasets: [pie]
  batch_size: [2, 2]
  epochs: [40, 40]  # [40, 40]
  lr: [5.0e-07, 5.0e-07]
