model_opts:
  model: PCPA_MULTI
  obs_input_type: [local_context_cnn, mask_cnn, box, speed]
  apply_class_weights: True
  normalize_boxes: True
  generator: True
  time_to_event: 15  # 30, 60, [30,60]
net_opts:
  num_hidden_units: 256
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: gru
  backbone: vgg19
exp_opts:
  datasets: [jaad_beh, jaad_all, pie]
  batch_size: [2, 2, 2]
  epochs: [80, 80, 80]  # [40, 40]
  lr: [5.0e-07, 5.0e-07, 5.0e-07]
