model_opts:
  model: PCPA_2D
  obs_input_type: [local_context, pose, box, speed]
  apply_class_weights: True
  normalize_boxes: True
  obs_length: 4 # observation length
  time_to_event: [30]  # 30, 60, [30,60]
  generator: True
net_opts:
  num_hidden_units: 8
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: gru
  backbone: c3d
exp_opts:
  datasets: [jaad_all]
  batch_size: [1]
  epochs: [5]
  lr: [5.0e-07]
data_opts:
  min_track_size: 16 # tracks shorter than this length will be discarded