model_opts: #
  model: TST_VISION
  obs_input_type: [local_cnn, mask_cnn, pose, box, speed]
  apply_class_weights: True
  normalize_boxes: True
  generator: True
  time_to_event: [30, 60]
  t_time2vec_dim: 1
  t_num_heads: 4
  t_head_size: 128
  t_num_layers: 2 # 2
  t_dropout: 0.4
net_opts:
  num_hidden_units: 256
  global_pooling: avg
  regularizer_val: 0.001
  cell_type: gru
  backbone: vgg19
exp_opts:
  datasets: [pie]
  batch_size: [2]
  epochs: [60]  # [80, 80, 60]
  lr: [5.0e-05] # pie -05?