model_opts:
  model: MASK_PCPA_4_2D
  obs_input_type: [local_cnn, mask_cnn, pose, box, speed] #local_context_cnn
  apply_class_weights: True
  normalize_boxes: True
  generator: True
  time_to_event: [30, 60]
net_opts:
  num_hidden_units: 256
  global_pooling: avg
  regularizer_val: 0.0001
  cell_type: gru
  backbone: vgg19 # efficientnet
exp_opts:
  datasets: [jaad_beh, jaad_all, pie] # [jaad_beh, jaad_all, pie]
  batch_size: [2, 2, 2] # [2, 2, 2]
  epochs: [80, 80, 60]  # [40, 40]
  lr: [5.0e-07, 5.0e-07, 5.0e-07]
